security:

    encoders:
        FOS\UserBundle\Model\UserInterface: "bcrypt"

    role_hierarchy:
        ROLE_ADMIN:       "ROLE_USER"
        ROLE_SUPER_ADMIN: ["ROLE_ADMIN", "ROLE_ALLOWED_TO_SWITCH"]

    providers:
        fos_userbundle:
            id: "fos_user.user_provider.username_email"

    firewalls:
        dev:
            pattern: "^/(_(profiler|wdt|error)|css|images|js)/"
            security: false

        main:
            pattern: "^/"
            anonymous: true
            form_login:
                provider: "fos_userbundle"
                csrf_token_generator: "security.csrf.token_manager"
                login_path: "/login"
                check_path: "/login_check"
            oauth:
                resource_owners:
                    google: "/login/check-google"
                    facebook: "/login/check-facebook"
                    twitter: "/login/check-twitter"
                login_path: "/connect/google"
                failure_path: "/login"
                default_target_path: "/welcome"
                oauth_user_provider:
                    service: "quickstart.oauth_user_provider"

        default:
            anonymous: ~

    access_control:
        - { path: "^/login", role: "IS_AUTHENTICATED_ANONYMOUSLY" }
        - { path: "^/connect", role: "IS_AUTHENTICATED_ANONYMOUSLY" }
        - { path: "^/user", role: "ROLE_USER" }
        - { path: "^/logout", role: "ROLE_USER" }
        - { path: "^/admin", role: "ROLE_ADMIN" }

