imports:

parameters:
    app.apcu.class: AppBundle\Services\Apcu
    app.google.class: AppBundle\Services\Google
    app.calendar.class: AppBundle\Services\Calendar
    app.twig.room.class: AppBundle\Twig\Extension\RoomExtension

services:
    app.apcu:
        class: '%app.apcu.class%'

    app.google:
        class: '%app.google.class%'
        parent: "base.service"
        arguments: ["@security.token_storage"]

    app.calendar:
        class: '%app.calendar.class%'
        parent: "base.service"

    app.twig.room:
       class: '%app.twig.room.class%'
       tags:
           - { name: twig.extension }
