fuz_quickstart:
    resource: '@FuzQuickStartBundle/Controller/'
    type: annotation
    prefix: /

fos_user:
    resource: '@FOSUserBundle/Resources/config/routing/all.xml'

hwi_oauth_redirect:
    resource: '@HWIOAuthBundle/Resources/config/routing/redirect.xml'
    prefix: /connect

hwi_oauth_connect:
    resource: '@HWIOAuthBundle/Resources/config/routing/connect.xml'
    prefix: /connect

google_login:
    path: /login/check-google

facebook_login:
    path: /login/check-facebook

twitter_login:
    path: /login/check-twitter
