parameters:
    base.service.class: Fuz\QuickStartBundle\Base\BaseService
    quickstart.oauth_user_provider.class: Fuz\QuickStartBundle\Provider\OAuthUserProvider
    hwi_oauth.account.connector.class: Fuz\QuickStartBundle\Connect\AccountConnect
    quickstart.locale.listener.class: Fuz\QuickStartBundle\EventListener\LocaleListener
    quickstart.last_route.listener.class: Fuz\QuickStartBundle\EventListener\LastRouteListener
    quickstart.fos_user_bundle.listener.class: Fuz\QuickStartBundle\EventListener\FOSUserBundleListener
    quickstart.toggle.listener.class: Fuz\QuickStartBundle\EventListener\ToggleListener
    quickstart.routing.class: Fuz\QuickStartBundle\Services\Routing
    quickstart.captcha.class: Fuz\QuickStartBundle\Services\Captcha
    quickstart.captcha.controller.class: Fuz\QuickStartBundle\Controller\CaptchaController
    quickstart.captcha.listener.class: Fuz\QuickStartBundle\EventListener\CaptchaListener

services:

    base.service:
        class: %base.service.class%
        abstract: true
        calls:
          - [setContainer, ["@service_container"]]

    quickstart.oauth_user_provider:
        class: '%quickstart.oauth_user_provider.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@fos_user.user_manager'
            - '%admins%'

    hwi_oauth.account.connector:
        class: '%hwi_oauth.account.connector.class%'

    quickstart.locale.listener:
        class: '%quickstart.locale.listener.class%'
        arguments:
            - '%kernel.default_locale%'
        tags:
            - { name: kernel.event_subscriber }

    quickstart.last_route.listener:
        class: '%quickstart.last_route.listener.class%'
        arguments:
            - '@quickstart.routing'
        tags:
            - { name: kernel.event_subscriber }

    quickstart.fos_user_bundle.listener:
        class: '%quickstart.fos_user_bundle.listener.class%'
        arguments:
            - '@fos_user.mailer'
            - '@fos_user.util.token_generator'
            - '@router'
            - '@session'
            - '@security.token_storage'
            - '@fos_user.user_manager'
            - '@translator'
        tags:
            - { name: kernel.event_subscriber }

    quickstart.toggle.listener:
        class: %quickstart.toggle.listener.class%
        parent: "base.service"
        tags:
            - { name: kernel.event_subscriber }

    quickstart.routing:
        class: '%quickstart.routing.class%'
        arguments:
            - '@router'

    quickstart.captcha:
        class: '%quickstart.captcha.class%'
        arguments:
            - '@logger'
            - '@session'
            - '@doctrine.orm.entity_manager'
            - '%no_captcha%'
        tags:
            - { name: monolog.logger, channel: services.captcha }

    quickstart.captcha.controller:
        class: '%quickstart.captcha.controller.class%'
        calls:
            - [setContainer, ['@service_container']]

    quickstart.captcha.listener:
        class: '%quickstart.captcha.listener.class%'
        arguments:
            - '@router'
            - '@quickstart.captcha'
            - '@quickstart.captcha.controller'
            - '%no_captcha%'
        tags:
            - { name: kernel.event_subscriber }
